changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bug Fixes 🛠
      labels:
        - bug
    - title: Enhancements 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
